name: test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to execute the tests'
        required: true
        default: 'INT'
        options:
          - TEST
          - INT
      
      grep:
        description: 'Execute tests with the following tags:'
        required: true
        default: '@regression'
        options:        
          - '@smoke'
          - '@regression'
          - ''

      country:
        description: 'For vse-reporting only - Country (code) '
        required: true
        default: 'ALL'
        type: choice
        options:
          - ALL
          - DE

          
jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: npx playwright test --grep "${{github.event.inputs.grep}}"
