name: Run Playwright tests
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set uo Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.5.0    
    - name: install Playwright
      run: npx playwright install  

    - name: Run Playwright tests
      run: npx playwright test
      
      
      
